apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosmartkickers-deploy
spec:
  selector:
    matchLabels:
      app: gosmartkickers
  template:
    metadata:
      labels:
        app: gosmartkickers
    spec:
      containers:
        - name: gosmartkickers
          image: smartkickers/backend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 100Mi
