apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartkickers
  labels:
    name: smartkickers
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gosmartkickers
                port:
                  number: 3000
