name: GO server Continous Integration Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
      - "!**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13.1"
      - name: "Install dependencies"
        run: go mod tidy
      - run: go test ./...
