name: GO server Continues Delivery Workflow

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"
      - "!**/*.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: docker login
        env:
          run: echo ${{secrets.GITHUB_TOKEN}} | docker login -u ${{github.actor}} --password-stdin ghcr.io
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag ghcr.io/smartkickers/smartkickers-backend:latest
      - name: Docker Push
        run: Docker push ghcr.io/smartkickers/smartkickers-backend
