name: React.JS Continous Integration Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - develop
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
      - "!**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/smart-kickers-game
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: npm ci
      - run: npm test

  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/smart-kickers-game
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - run: npx prettier --check .
